/**
 * Migration: Transfer Pairing — Phase 3.0
 *
 * Adds the data model required for paired internal transfers.
 * Two new columns on `transactions`:
 *
 *   transfer_group_id UUID NULL
 *     Shared identifier for both legs of an internal transfer.
 *     Both the outbound and inbound transaction receive the same UUID.
 *     NULL = standalone transfer (external, or old pre-migration data).
 *
 *   transfer_direction TEXT NULL  ('outbound' | 'inbound')
 *     Determines the balance sign for this leg:
 *       outbound → money LEFT the account  → SUBTRACTED from balance
 *       inbound  → money ARRIVED           → ADDED to balance
 *     NULL = old data; treated as 'outbound' by application code (safe default).
 *
 * One new column on `transaction_drafts`:
 *   transfer_target_account_id UUID NULL FK → account_sources
 *     Set by bot UI when user picks the destination account.
 *     NULL = user hasn't chosen yet, or not a transfer draft.
 *
 * Backward compatibility:
 *   - All existing 'transfer' transactions are backfilled with direction='outbound'.
 *     This preserves the current behaviour (transfers reduce the account balance).
 *   - transfer_group_id stays NULL for old rows (no pair = standalone).
 *   - All existing queries continue to work unchanged.
 *
 * Balance formula note (must be updated in application code simultaneously):
 *   OLD: - SUM(transfer)
 *   NEW: + SUM(transfer WHERE direction='inbound')
 *        - SUM(transfer WHERE direction='outbound' OR direction IS NULL)
 *
 * SEC-03: DDL migration — no tenant context needed.
 * ADR-004: ULIDs are generated by application layer, not DB.
 */

export const shorthands = undefined;

export const up = (pgm) => {
  pgm.sql(`
    -- ── Step 1: Add transfer_group_id ───────────────────────────────────────
    -- Neutral shared UUID generated by backend when creating the pair.
    -- Both outbound and inbound legs receive the same value atomically.

    ALTER TABLE transactions
      ADD COLUMN transfer_group_id UUID NULL;

    -- Index for looking up the sibling transaction efficiently.
    CREATE INDEX idx_transactions_transfer_group
      ON transactions (transfer_group_id)
      WHERE transfer_group_id IS NOT NULL;

    -- ── Step 2: Add transfer_direction ───────────────────────────────────────
    -- Determines whether this leg adds or subtracts from the account balance.

    ALTER TABLE transactions
      ADD COLUMN transfer_direction TEXT NULL;

    ALTER TABLE transactions
      ADD CONSTRAINT chk_transfer_direction
      CHECK (transfer_direction IS NULL OR transfer_direction IN ('outbound', 'inbound'));

    -- ── Step 3: Add transfer_target_account_id to drafts ────────────────────
    -- Set by bot UI after user selects the destination account.
    -- ON DELETE SET NULL: if the target account is hard-deleted, draft stays valid
    -- (user will be prompted to re-select).

    ALTER TABLE transaction_drafts
      ADD COLUMN transfer_target_account_id TEXT NULL
      REFERENCES account_sources(id) ON DELETE SET NULL;

    -- ── Step 4: Backfill direction for existing transfer records ─────────────
    -- Old transfers always reduced the balance (same as 'outbound' semantics).
    -- transfer_group_id stays NULL — no pair exists for legacy records.

    UPDATE transactions
      SET transfer_direction = 'outbound'
      WHERE transaction_intent = 'transfer'
        AND transfer_direction IS NULL;

    -- ── Verify backfill (advisory — will appear in migration log) ────────────
    -- DO $$
    -- DECLARE cnt INT;
    -- BEGIN
    --   SELECT COUNT(*) INTO cnt FROM transactions
    --     WHERE transaction_intent = 'transfer' AND transfer_direction IS NULL;
    --   IF cnt > 0 THEN
    --     RAISE EXCEPTION 'Backfill incomplete: % rows still have NULL direction', cnt;
    --   END IF;
    -- END $$;
  `);
};

export const down = (pgm) => {
  pgm.sql(`
    -- Reverse in correct dependency order.

    ALTER TABLE transaction_drafts
      DROP COLUMN IF EXISTS transfer_target_account_id;

    ALTER TABLE transactions
      DROP CONSTRAINT IF EXISTS chk_transfer_direction;

    ALTER TABLE transactions
      DROP COLUMN IF EXISTS transfer_direction;

    DROP INDEX IF EXISTS idx_transactions_transfer_group;

    ALTER TABLE transactions
      DROP COLUMN IF EXISTS transfer_group_id;
  `);
};
