/**
 * Draft Confirmation Service — Phase 1.6-B / Phase 1.8-A / Phase 1.25
 *
 * Implements atomic approve/reject for TransactionDraft records.
 *
 * Phase 1.8-A addition:
 *   - parsed_intent is now fetched from the draft during SELECT FOR UPDATE.
 *   - transaction_intent is written to transactions during INSERT.
 *   - If parsed_intent IS NULL when a draft is approved, the approval fails safely
 *     with outcome 'intent_missing'. No Transaction is created. This prevents
 *     silent data corruption — every Transaction must have a known intent.
 *
 * Race condition protection:
 *   - SELECT ... FOR UPDATE SKIP LOCKED prevents two concurrent workers from
 *     processing the same draft simultaneously.
 *   - The draft status is checked inside the locked transaction. If status is
 *     not 'pending_user', the operation is a no-op (idempotent).
 *   - transactions.draft_id has UNIQUE constraint → second INSERT would fail
 *     even if SELECT FOR UPDATE fails (defence in depth).
 *
 * SEC-03: ALL DB ops use withTenantTransaction(workspaceId, userId, fn).
 * SEC-02: No float arithmetic. Amount read from draft.parsed_amount (NUMERIC in DB).
 * ADR-004: Transaction ID = ULID generated by backend.
 * Draft state machine (migration 1777973834059): DB trigger enforces valid transitions.
 */

import { ulid } from 'ulid';
import { withTenantTransaction } from '@midas/database';

// ─────────────────────────────────────────────────────────────
// Types
// ─────────────────────────────────────────────────────────────

export type ConfirmActionResult =
  | { outcome: 'approved'; transactionId: string }
  | { outcome: 'rejected' }
  | { outcome: 'already_processed'; existingStatus: string }
  | { outcome: 'not_found' }
  | { outcome: 'expired' }
  | { outcome: 'intent_missing' }; // Phase 1.8-A: draft has NULL parsed_intent — cannot create Transaction

// ─────────────────────────────────────────────────────────────
// approveDraft
// ─────────────────────────────────────────────────────────────

/**
 * Atomically approve a TransactionDraft.
 *
 * Flow (all inside one withTenantTransaction):
 *   1. SELECT ... FOR UPDATE SKIP LOCKED — lock the draft row.
 *      If another worker has it locked, SKIP LOCKED returns 0 rows → no-op.
 *   2. Validate: draft must exist, belong to workspace, be pending_user, and not expired.
 *   3. Phase 1.8-A: validate parsed_intent is not NULL. If NULL → return intent_missing.
 *   4. UPDATE transaction_drafts SET status = 'approved'.
 *      The DB trigger (enforce_draft_state_machine) also validates expiry.
 *   5. INSERT INTO transactions with transaction_intent (Phase 1.8-A: explicit, no default).
 *
 * @param draftId - ULID of the draft to approve
 * @param workspaceId - Workspace ID (SEC-03: from backend session, not from callback_data)
 * @param userId - User ID for RLS context (SEC-03)
 * @returns ConfirmActionResult with outcome
 */
export async function approveDraft(
  draftId: string,
  workspaceId: string,
  userId: string,
): Promise<ConfirmActionResult> {
  return withTenantTransaction(workspaceId, userId, async (client) => {
    // ── Step 1: Lock draft row for atomic update ──────────────
    // SKIP LOCKED: if another worker already has this row locked,
    // we get 0 rows and return immediately (not an error — idempotent).
    const lockResult = await client.query<{
      id: string;
      workspace_id: string;
      status: string;
      parsed_amount: string | null;
      parsed_currency: string | null;
      parsed_intent: string | null;  // Phase 1.8-A: must be non-NULL for Transaction creation
      expires_at: string;
    }>(
      `SELECT id, workspace_id, status, parsed_amount, parsed_currency, parsed_intent, expires_at
       FROM transaction_drafts
       WHERE id = $1 AND workspace_id = $2
       FOR UPDATE SKIP LOCKED`,
      [draftId, workspaceId],
    );

    // ── Step 2: Check if we got the lock ─────────────────────
    if (lockResult.rows.length === 0) {
      // Either not found (wrong workspace) or locked by another worker.
      // Query without lock to distinguish:
      const checkResult = await client.query<{ status: string }>(
        `SELECT status FROM transaction_drafts WHERE id = $1`,
        [draftId],
      );
      if (checkResult.rows.length === 0) {
        return { outcome: 'not_found' };
      }
      // Row exists but locked by another worker → they're processing it.
      const existingStatus = checkResult.rows[0]?.status ?? 'unknown';
      return { outcome: 'already_processed', existingStatus };
    }

    const draft = lockResult.rows[0];
    if (!draft) return { outcome: 'not_found' }; // Defensive — should not happen after length check

    // ── Step 3: Validate status ───────────────────────────────
    if (draft.status !== 'pending_user') {
      return { outcome: 'already_processed', existingStatus: draft.status };
    }

    // ── Step 4: Check expiry ──────────────────────────────────
    const expiresAt = new Date(draft.expires_at);
    if (expiresAt <= new Date()) {
      // Update to expired to clean up state — DB trigger allows pending_user → expired
      await client.query(
        `UPDATE transaction_drafts SET status = 'expired', updated_at = NOW() WHERE id = $1`,
        [draftId],
      );
      return { outcome: 'expired' };
    }

    // ── Step 5: Phase 1.8-A — Validate intent before committing ──────────────────
    // parsed_intent must not be NULL. A Transaction without a known intent is
    // semantically invalid and would corrupt future /report queries.
    // Fail safely: do NOT update draft status, do NOT create Transaction.
    // The user can resend the message to create a new draft with valid intent.
    if (draft.parsed_intent === null) {
      console.warn('[midas:draft-confirmation] Approval blocked: parsed_intent is NULL', {
        draftId,
        workspaceId,
        // No raw_text logged (SEC-12)
      });
      return { outcome: 'intent_missing' };
    }

    // ── Step 6: Update draft status to approved ───────────────
    // DB trigger (enforce_draft_state_machine) will re-validate expiry and terminal state.
    await client.query(
      `UPDATE transaction_drafts SET status = 'approved', updated_at = NOW() WHERE id = $1`,
      [draftId],
    );

    // ── Step 7: Create Transaction from draft ─────────────────
    // SEC-02: parsed_amount is a NUMERIC string from DB — passed directly to NUMERIC column.
    // No parseFloat(), no Number() — the DB handles precision.
    // Phase 1.6-B: exchange_rate = 1, base_amount = parsed_amount (same currency).
    // Full multi-currency support: Phase 2 (ADR-009 exchange rate snapshots).
    const transactionId = ulid(); // ADR-004: ULID generated by backend (SEC-01)

    // Phase 1.25: Fetch workspace default_currency BEFORE resolving transaction currency.
    // Used as fallback when AI does not parse an explicit currency from the message.
    // Replaces hardcoded 'USD' fallback — ensures transactions use the workspace's
    // configured default (e.g. USDT for new users, or whatever /settings currency set).
    const wsResult = await client.query<{ default_currency: string }>(
      `SELECT default_currency FROM workspaces WHERE id = $1`,
      [workspaceId],
    );
    const baseCurrency = wsResult.rows[0]?.default_currency ?? 'USDT';

    // Workspace default_currency for base_currency (same SELECT result reused above).
    // Phase 1.25: fallback is baseCurrency (workspace default), not hardcoded 'USD'.
    const currency = draft.parsed_currency ?? baseCurrency;

    // Determine category_id: use workspace first category or create a default one.
    // Phase 1.6-B placeholder — fuzzy matching deferred to future phase.
    // categories.group is an ENUM: 'Бизнес' | 'Жизнь'
    const catResult = await client.query<{ id: string }>(
      `SELECT id FROM categories WHERE workspace_id = $1 LIMIT 1`,
      [workspaceId],
    );
    let categoryId: string;
    if (catResult.rows.length === 0) {
      categoryId = ulid();
      await client.query(
        `INSERT INTO categories (id, workspace_id, name, "group")
         VALUES ($1, $2, 'Разное', 'Жизнь'::category_group)
         ON CONFLICT (workspace_id, name) DO NOTHING`,
        [categoryId, workspaceId],
      );
      // Refetch after possible conflict
      const refetch = await client.query<{ id: string }>(
        `SELECT id FROM categories WHERE workspace_id = $1 AND name = 'Разное' LIMIT 1`,
        [workspaceId],
      );
      categoryId = refetch.rows[0]?.id ?? categoryId;
    } else {
      categoryId = catResult.rows[0]?.id ?? ulid();
    }

    // Determine account_id: use workspace first account source or create a default one.
    // account_sources.type is an ENUM: 'manual' | 'crypto_read_only' | 'bank_sync'
    const acctResult = await client.query<{ id: string }>(
      `SELECT id FROM account_sources WHERE workspace_id = $1 LIMIT 1`,
      [workspaceId],
    );
    let accountId: string;
    if (acctResult.rows.length === 0) {
      accountId = ulid();
      await client.query(
        `INSERT INTO account_sources (id, workspace_id, name, type, currency)
         VALUES ($1, $2, 'Default', 'manual'::account_source_type, $3)
         ON CONFLICT DO NOTHING`,
        [accountId, workspaceId, currency],
      );
      const refetch = await client.query<{ id: string }>(
        `SELECT id FROM account_sources WHERE workspace_id = $1 AND name = 'Default' LIMIT 1`,
        [workspaceId],
      );
      accountId = refetch.rows[0]?.id ?? accountId;
    } else {
      accountId = acctResult.rows[0]?.id ?? ulid();
    }

    await client.query(
      `INSERT INTO transactions (
        id,
        workspace_id,
        original_amount,
        currency,
        exchange_rate,
        base_currency,
        base_amount,
        category_id,
        account_id,
        draft_id,
        transaction_time,
        transaction_intent,
        rate_source,
        created_at
      ) VALUES (
        $1, $2,
        $3::NUMERIC,        -- original_amount from draft.parsed_amount (SEC-02: no float)
        $4,
        1::NUMERIC,         -- exchange_rate = 1:1 (Phase 1.6-B; multi-currency Phase 2)
        $5,
        $3::NUMERIC,        -- base_amount = original_amount (same currency, Phase 1.6-B)
        $6,                 -- category_id
        $7,                 -- account_id
        $8,                 -- draft_id (UNIQUE FK)
        NOW(),
        $9,                 -- transaction_intent (Phase 1.8-A: explicit, no default)
        'none',             -- rate_source: Phase 1.6-B placeholder (ADR-009 Phase 2)
        NOW()
      )`,
      [
        transactionId,              // $1 — ULID (ADR-004, SEC-01: not from AI)
        workspaceId,                // $2 — SEC-03: from backend session
        draft.parsed_amount ?? '0', // $3 — NUMERIC string from DB (SEC-02)
        currency,                   // $4
        baseCurrency,               // $5
        categoryId,                 // $6
        accountId,                  // $7
        draftId,                    // $8
        draft.parsed_intent,        // $9 — Phase 1.8-A: non-NULL validated in Step 5
      ],
    );

    console.log('[midas:draft-confirmation] Draft approved and Transaction created', {
      draftId,
      transactionId,
      workspaceId,
      transactionIntent: draft.parsed_intent, // safe to log: classification value (SEC-12)
      // amount deliberately NOT logged (SEC-12)
    });

    return { outcome: 'approved', transactionId };
  });
}

// ─────────────────────────────────────────────────────────────
// rejectDraft
// ─────────────────────────────────────────────────────────────

/**
 * Atomically reject a TransactionDraft.
 *
 * Flow:
 *   1. SELECT ... FOR UPDATE SKIP LOCKED — lock the draft row.
 *   2. Validate: must be pending_user.
 *   3. UPDATE status = 'rejected'.
 *   No Transaction is created.
 */
export async function rejectDraft(
  draftId: string,
  workspaceId: string,
  userId: string,
): Promise<ConfirmActionResult> {
  return withTenantTransaction(workspaceId, userId, async (client) => {
    // ── Step 1: Lock draft row ────────────────────────────────
    const lockResult = await client.query<{ id: string; status: string }>(
      `SELECT id, status
       FROM transaction_drafts
       WHERE id = $1 AND workspace_id = $2
       FOR UPDATE SKIP LOCKED`,
      [draftId, workspaceId],
    );

    if (lockResult.rows.length === 0) {
      const checkResult = await client.query<{ status: string }>(
        `SELECT status FROM transaction_drafts WHERE id = $1`,
        [draftId],
      );
      if (checkResult.rows.length === 0) {
        return { outcome: 'not_found' };
      }
      const existingStatus = checkResult.rows[0]?.status ?? 'unknown';
      return { outcome: 'already_processed', existingStatus };
    }

    const draft = lockResult.rows[0];
    if (!draft) return { outcome: 'not_found' }; // Defensive — should not happen after length check

    // ── Step 2: Validate status ───────────────────────────────
    if (draft.status !== 'pending_user') {
      return { outcome: 'already_processed', existingStatus: draft.status };
    }

    // ── Step 3: Update to rejected ────────────────────────────
    await client.query(
      `UPDATE transaction_drafts SET status = 'rejected', updated_at = NOW() WHERE id = $1`,
      [draftId],
    );

    console.log('[midas:draft-confirmation] Draft rejected', {
      draftId,
      workspaceId,
    });

    return { outcome: 'rejected' };
  });
}
