/**
 * Draft Confirmation Service — Phase 1.6-B / Phase 1.8-A / Phase 1.25 / Phase 1.35
 *
 * Implements atomic approve/reject for TransactionDraft records.
 *
 * Phase 1.8-A addition:
 *   - parsed_intent is now fetched from the draft during SELECT FOR UPDATE.
 *   - transaction_intent is written to transactions during INSERT.
 *   - If parsed_intent IS NULL when a draft is approved, the approval fails safely
 *     with outcome 'intent_missing'. No Transaction is created. This prevents
 *     silent data corruption — every Transaction must have a known intent.
 *
 * Race condition protection:
 *   - SELECT ... FOR UPDATE SKIP LOCKED prevents two concurrent workers from
 *     processing the same draft simultaneously.
 *   - The draft status is checked inside the locked transaction. If status is
 *     not 'pending_user', the operation is a no-op (idempotent).
 *   - transactions.draft_id has UNIQUE constraint → second INSERT would fail
 *     even if SELECT FOR UPDATE fails (defence in depth).
 *
 * SEC-03: ALL DB ops use withTenantTransaction(workspaceId, userId, fn).
 * SEC-02: No float arithmetic. Amount read from draft.parsed_amount (NUMERIC in DB).
 * ADR-004: Transaction ID = ULID generated by backend.
 * Draft state machine (migration 1777973834059): DB trigger enforces valid transitions.
 */

import { ulid } from 'ulid';
import { withTenantTransaction } from '@midas/database';
import { resolveCategory } from './category-resolver.service.js';

// ─────────────────────────────────────────────────────────────
// Types
// ─────────────────────────────────────────────────────────────

export type ConfirmActionResult =
  | {
      outcome: 'approved';
      transactionId: string;
      // Phase 1.34: display data for rich post-confirmation card
      amount: string;           // NUMERIC string from DB (SEC-02) — tx amount
      currency: string;         // e.g. 'USDT'
      categoryName: string;     // resolved name or fallback
      accountName: string;      // resolved name or fallback
      intent: string;           // transaction_intent
      itemName: string | null;  // Phase 1.35: item/product/merchant name
      transactionTime: string;  // ISO string
      // Phase 2.4 PR13: balance snapshot for "Итог" block
      accountCurrency: string | null;    // account currency (may differ from tx currency)
      balanceBefore: string | null;      // balance BEFORE transaction (NUMERIC string)
      balanceAfter: string | null;       // balance AFTER transaction (NUMERIC string)
      debitAmount: string | null;        // cross-currency debit amount in account currency
      debitCurrency: string | null;      // currency of debitAmount
    }
  | { outcome: 'rejected' }
  | {
      outcome: 'already_processed';
      existingStatus: string;
      // Present when existingStatus === 'approved' — for rich re-display
      approvedCard?: {
        transactionId: string;
        amount: string;
        currency: string;
        categoryName: string;
        accountName: string;
        intent: string;
        itemName: string | null;
        // Phase 2.4 PR13: balance snapshot (may be null if tx is old)
        accountCurrency?: string | null;
        balanceBefore?: string | null;
        balanceAfter?: string | null;
        debitAmount?: string | null;
        debitCurrency?: string | null;
      };
    }
  | { outcome: 'not_found' }
  | { outcome: 'expired' }
  | { outcome: 'intent_missing' }; // Phase 1.8-A: draft has NULL parsed_intent — cannot create Transaction

// ─────────────────────────────────────────────────────────────
// approveDraft
// ─────────────────────────────────────────────────────────────

/**
 * Atomically approve a TransactionDraft.
 *
 * Flow (all inside one withTenantTransaction):
 *   1. SELECT ... FOR UPDATE SKIP LOCKED — lock the draft row.
 *      If another worker has it locked, SKIP LOCKED returns 0 rows → no-op.
 *   2. Validate: draft must exist, belong to workspace, be pending_user, and not expired.
 *   3. Phase 1.8-A: validate parsed_intent is not NULL. If NULL → return intent_missing.
 *   4. UPDATE transaction_drafts SET status = 'approved'.
 *      The DB trigger (enforce_draft_state_machine) also validates expiry.
 *   5. INSERT INTO transactions with transaction_intent (Phase 1.8-A: explicit, no default).
 *
 * @param draftId - ULID of the draft to approve
 * @param workspaceId - Workspace ID (SEC-03: from backend session, not from callback_data)
 * @param userId - User ID for RLS context (SEC-03)
 * @returns ConfirmActionResult with outcome
 */
export async function approveDraft(
  draftId: string,
  workspaceId: string,
  userId: string,
): Promise<ConfirmActionResult> {
  return withTenantTransaction(workspaceId, userId, async (client) => {
    // ── Step 1: Lock draft row for atomic update ──────────────
    // SKIP LOCKED: if another worker already has this row locked,
    // we get 0 rows and return immediately (not an error — idempotent).
    const lockResult = await client.query<{
      id: string;
      workspace_id: string;
      status: string;
      parsed_amount: string | null;
      parsed_currency: string | null;
      parsed_intent: string | null;  // Phase 1.8-A: must be non-NULL for Transaction creation
      parsed_account_hint: string | null; // Phase 1.31
      parsed_category_hint: string | null; // Phase 1.35
      item_name: string | null;            // Phase 1.35
      account_id: string | null;          // Phase 1.31: set by ia: callback before approval
      account_debit_amount: string | null; // Phase 2.4 PR12: cross-currency override
      account_debit_currency: string | null; // Phase 2.4 PR12
      expires_at: string;
    }>(
      `SELECT id, workspace_id, status, parsed_amount, parsed_currency, parsed_intent,
              parsed_account_hint, parsed_category_hint, item_name, account_id,
              account_debit_amount, account_debit_currency, expires_at
       FROM transaction_drafts
       WHERE id = $1 AND workspace_id = $2
       FOR UPDATE SKIP LOCKED`,
      [draftId, workspaceId],
    );

    // ── Step 2: Check if we got the lock ─────────────────────
    if (lockResult.rows.length === 0) {
      // Either not found (wrong workspace) or locked by another worker.
      // Query without lock to distinguish:
      const checkResult = await client.query<{ status: string }>(
        `SELECT status FROM transaction_drafts WHERE id = $1`,
        [draftId],
      );
      if (checkResult.rows.length === 0) {
        return { outcome: 'not_found' };
      }
      // Row exists but locked by another worker → they're processing it.
      const existingStatus = checkResult.rows[0]?.status ?? 'unknown';
      return { outcome: 'already_processed', existingStatus };
    }

    const draft = lockResult.rows[0];
    if (!draft) return { outcome: 'not_found' }; // Defensive — should not happen after length check

    // ── Step 3: Validate status ───────────────────────────────
    if (draft.status !== 'pending_user') {
      return { outcome: 'already_processed', existingStatus: draft.status };
    }

    // ── Step 4: Check expiry ──────────────────────────────────
    const expiresAt = new Date(draft.expires_at);
    if (expiresAt <= new Date()) {
      // Update to expired to clean up state — DB trigger allows pending_user → expired
      await client.query(
        `UPDATE transaction_drafts SET status = 'expired', updated_at = NOW() WHERE id = $1`,
        [draftId],
      );
      return { outcome: 'expired' };
    }

    // ── Step 5: Phase 1.8-A — Validate intent before committing ──────────────────
    // parsed_intent must not be NULL. A Transaction without a known intent is
    // semantically invalid and would corrupt future /report queries.
    // Fail safely: do NOT update draft status, do NOT create Transaction.
    // The user can resend the message to create a new draft with valid intent.
    if (draft.parsed_intent === null) {
      console.warn('[midas:draft-confirmation] Approval blocked: parsed_intent is NULL', {
        draftId,
        workspaceId,
        // No raw_text logged (SEC-12)
      });
      return { outcome: 'intent_missing' };
    }

    // ── Step 6: Update draft status to approved ───────────────
    // DB trigger (enforce_draft_state_machine) will re-validate expiry and terminal state.
    await client.query(
      `UPDATE transaction_drafts SET status = 'approved', updated_at = NOW() WHERE id = $1`,
      [draftId],
    );

    // ── Step 7: Create Transaction from draft ─────────────────
    // SEC-02: parsed_amount is a NUMERIC value from DB. Due to
    // pg.types.setTypeParser(1700, val => new Decimal(val)) in db.ts,
    // it arrives as a Decimal OBJECT even though typed as `string | null`.
    // We must convert to a plain string before passing it back as a query
    // parameter — otherwise node-pg calls JSON.stringify(Decimal) which
    // produces '"1000"' (string with embedded quotes), and Postgres
    // rejects it with 'invalid input syntax for type numeric'.
    // eslint-disable-next-line @typescript-eslint/no-unnecessary-type-conversion -- runtime type is Decimal, not string
    const amountStr = String(draft.parsed_amount ?? '0');
    const transactionId = ulid(); // ADR-004: ULID generated by backend (SEC-01)

    // Phase 1.25: Fetch workspace default_currency as fallback only.
    // Used when AI does not parse an explicit currency from the message.
    const wsResult = await client.query<{ default_currency: string }>(
      `SELECT default_currency FROM workspaces WHERE id = $1`,
      [workspaceId],
    );
    const workspaceDefaultCurrency = wsResult.rows[0]?.default_currency ?? 'USDT';

    // currency = the actual transaction currency (AI-parsed or workspace default fallback).
    // base_currency MUST equal currency (Phase 1.6-B: 1:1 exchange rate, no conversion yet).
    // Bug fix: previously baseCurrency (workspace default) was used for base_currency,
    // causing balance mismatch when transaction currency ≠ workspace default currency
    // (e.g. USD transaction on a USD account with USDT workspace default → balance = 0).
    const currency = draft.parsed_currency ?? workspaceDefaultCurrency;

    // Determine category_id: Phase 1.35 — use resolver pipeline.
    // Pipeline: exact match → alias map → auto-create → fallback "Другое".
    const categoryId = await resolveCategory(client, workspaceId, draft.parsed_category_hint);

    // Determine account_id: Phase 1.31 — use draft.account_id if set by ia: handler.
    // Phase 1.35: Fall back to workspace default account by intent.
    // Otherwise fall back to workspace first account source or create a Default.
    let accountId: string;
    let accountWasExplicitlyChosen = false; // Phase 2.4 PR17: track if user picked the account

    if (draft.account_id) {
      // Phase 1.31: account was resolved inline by user via ia: callback.
      const acctCheck = await client.query<{ id: string }>(
        `SELECT id FROM account_sources WHERE id = $1 AND workspace_id = $2`,
        [draft.account_id, workspaceId],
      );
      if (acctCheck.rows.length > 0) {
        accountId = draft.account_id;
        accountWasExplicitlyChosen = true;
      } else {
        // IDOR guard: account not in workspace — fall back to default
        accountId = await resolveDefaultAccount(client, workspaceId, currency, draft.parsed_intent);
      }
    } else {
      // Phase 1.35: Use workspace default account by intent.
      accountId = await resolveDefaultAccount(client, workspaceId, currency, draft.parsed_intent);
    }

    // Phase 2.4 PR17: Fetch the resolved account's currency.
    // When account was auto-resolved (not explicitly chosen) and its currency ≠ tx currency,
    // we do NOT record a cross-currency entry — user did not confirm debit amount.
    // Keep base_currency = tx currency so the Итог block remains accurate.
    const resolvedAcctRow = await client.query<{ currency: string }>(
      `SELECT currency FROM account_sources WHERE id = $1`,
      [accountId],
    );
    const resolvedAcctCurrency = resolvedAcctRow.rows[0]?.currency ?? currency;
    const accountCurrencyMismatch = resolvedAcctCurrency !== currency;
    // If mismatch AND user didn't explicitly choose account AND no debit override set →
    // treat as same-currency: base_currency = tx currency.
    // This prevents "200 USD → карта Амира RUB → Итог: -200 RUB" confusion.
    if (accountCurrencyMismatch && !accountWasExplicitlyChosen) {
      console.warn('[midas:draft-confirmation] Auto-resolved account currency mismatch', {
        draftId, workspaceId,
        txCurrency: currency,
        accountCurrency: resolvedAcctCurrency,
        // No names/amounts logged (SEC-12)
      });
    }

    // ── Phase 2.4 PR14: Compute XFX rate fields ───────────────────────────────
    // If account_debit_amount is set AND account_debit_currency ≠ tx currency,
    // this is a cross-currency (XFX) transaction.
    // We compute:
    //   exchange_rate = debitAmount / txAmount (as NUMERIC, 4 decimal places)
    //   base_amount   = debitAmount  (the actual money that left the account)
    //   base_currency = accountCurrency
    //   rate_source   = 'user'  (amount provided by user, not from a rate API)
    //
    // For same-currency transactions: keep Phase 1.6-B 1:1 logic.
    // SEC-02: All arithmetic in PostgreSQL NUMERIC via ROUND($N::NUMERIC / $M::NUMERIC, 4).
    const debitAmtStr = draft.account_debit_amount ? String(draft.account_debit_amount) : null;
    const debitCurStr = draft.account_debit_currency ?? null;
    const isXfx = debitAmtStr !== null && debitCurStr !== null && debitCurStr !== currency;

    // Fetch account currency for base_currency in XFX case.
    // Use debitCurStr directly — it was validated by the CHECK constraint on draft write.
    const baseCurrency = isXfx ? debitCurStr : currency;
    const baseAmount   = isXfx ? debitAmtStr : amountStr;
    // exchange_rate computed in SQL to keep NUMERIC precision (SEC-02).
    // For 1:1 we pass the literal 1; for XFX we pass it as a ratio expression.
    // Use parameterized SQL fragment per case to avoid float intermediate values.

    await client.query(
      `INSERT INTO transactions (
        id,
        workspace_id,
        original_amount,
        currency,
        exchange_rate,
        base_currency,
        base_amount,
        category_id,
        account_id,
        draft_id,
        item_name,
        transaction_time,
        transaction_intent,
        rate_source,
        account_debit_amount,
        account_debit_currency,
        created_at
      ) VALUES (
        $1, $2,
        $3::NUMERIC,                 -- original_amount (tx amount in tx currency)
        $4,                          -- currency (tx currency, AI-parsed or ws default)
        CASE
          WHEN $11::BOOLEAN           -- isXfx flag
          THEN ROUND($12::NUMERIC / NULLIF($3::NUMERIC, 0), 4)  -- debitAmt / txAmt
          ELSE 1::NUMERIC             -- Phase 1.6-B: 1:1 for same-currency
        END,
        $5,                          -- base_currency
        $13::NUMERIC,                -- base_amount (debitAmt for XFX, txAmt otherwise)
        $6,                          -- category_id
        $7,                          -- account_id
        $8,                          -- draft_id (UNIQUE FK)
        $9,                          -- item_name (Phase 1.35)
        NOW(),
        $10,                         -- transaction_intent (non-NULL, validated at Step 5)
        CASE WHEN $11::BOOLEAN THEN 'user' ELSE 'none' END,  -- rate_source
        CASE WHEN $14::TEXT IS NOT NULL THEN $14::NUMERIC ELSE NULL END,  -- account_debit_amount
        $15,                         -- account_debit_currency
        NOW()
      )`,
      [
        transactionId,              // $1  — ULID (ADR-004, SEC-01)
        workspaceId,                // $2  — SEC-03: from backend session
        amountStr,                  // $3  — tx amount (NUMERIC string)
        currency,                   // $4  — tx currency
        baseCurrency,               // $5  — base_currency (acct currency for XFX)
        categoryId,                 // $6  — Phase 1.35
        accountId,                  // $7
        draftId,                    // $8
        draft.item_name ?? null,    // $9  — Phase 1.35
        draft.parsed_intent,        // $10 — Phase 1.8-A
        isXfx,                      // $11 — XFX flag (boolean)
        debitAmtStr ?? amountStr,   // $12 — debitAmt for rate calc (fallback to txAmt)
        baseAmount,                 // $13 — base_amount
        debitAmtStr,                // $14 — account_debit_amount (NULL for same-currency)
        debitCurStr,                // $15 — account_debit_currency (NULL for same-currency)
      ],
    );


    console.log('[midas:draft-confirmation] Draft approved and Transaction created', {
      draftId,
      transactionId,
      workspaceId,
      transactionIntent: draft.parsed_intent, // safe to log: classification value (SEC-12)
      // amount deliberately NOT logged (SEC-12)
    });

    // Phase 1.34: Fetch display names for rich post-confirmation card.
    const catNameResult = await client.query<{ name: string }>(
      `SELECT name FROM categories WHERE id = $1 AND workspace_id = $2`,
      [categoryId, workspaceId],
    );
    const acctDataResult = await client.query<{ name: string; currency: string }>(
      `SELECT name, currency FROM account_sources WHERE id = $1 AND workspace_id = $2`,
      [accountId, workspaceId],
    );
    const acctData     = acctDataResult.rows[0];
    const acctName     = acctData?.name ?? 'Счёт';
    const acctCurrency = acctData?.currency ?? currency;

    // Phase 2.4 PR13: fetch balance AFTER transaction using the same formula as balance.service.ts.
    // We compute it inline (no view dependency) with the same D1-D3 sign rules.
    // IMPORTANT: this query runs AFTER INSERT, so the newly created transaction IS included.
    // balanceBefore = numericReverse(balanceAfter, debitAmount, isIncome).
    // SEC-02: All arithmetic in PostgreSQL NUMERIC — no JS float.
    const balanceSnapResult = await client.query<{ balance: string }>(
      `SELECT (
         a.initial_balance
         + COALESCE(SUM(CASE WHEN t.transaction_intent = 'income'        AND t.base_currency = a.currency THEN t.base_amount END), 0)
         + COALESCE(SUM(CASE WHEN t.transaction_intent = 'debt_received' AND t.base_currency = a.currency THEN t.base_amount END), 0)
         - COALESCE(SUM(CASE WHEN t.transaction_intent = 'expense'       AND t.base_currency = a.currency THEN t.base_amount END), 0)
         - COALESCE(SUM(CASE WHEN t.transaction_intent = 'debt_given'    AND t.base_currency = a.currency THEN t.base_amount END), 0)
         - COALESCE(SUM(CASE WHEN t.transaction_intent = 'transfer'      AND t.base_currency = a.currency THEN t.base_amount END), 0)
       )::TEXT AS balance
       FROM account_sources a
       LEFT JOIN transactions t
         ON t.account_id = a.id
        AND t.workspace_id = $1
        AND t.deleted_at IS NULL
       WHERE a.id = $2 AND a.workspace_id = $1
       GROUP BY a.id, a.initial_balance`,
      [workspaceId, accountId],
    );
    const balanceAfterRaw   = balanceSnapResult.rows[0]?.balance ?? null;
    const acctCurrencyFinal = acctCurrency;

    // Debit amount in account currency: explicit xfx override or tx amount (same currency).
    const debitAmountRaw = draft.account_debit_amount ?? amountStr;

    // Compute balanceBefore by reversing the balance step.
    // SEC-02: BigInt arithmetic via numericReverse() helper below.
    let balanceBeforeRaw: string | null = null;
    if (balanceAfterRaw !== null) {
      try {
        const isIncome = draft.parsed_intent === 'income' || draft.parsed_intent === 'debt_received';
        balanceBeforeRaw = numericReverse(balanceAfterRaw, debitAmountRaw, isIncome);
      } catch { /* non-fatal: balanceBefore stays null */ }
    }

    return {
      outcome: 'approved',
      transactionId,
      amount: amountStr,  // String-coerced Decimal (SEC-02)
      currency,
      categoryName: catNameResult.rows[0]?.name ?? 'Другое',
      accountName: acctName,
      intent: draft.parsed_intent,  // Validated non-null at Step 5
      itemName: draft.item_name ?? null,  // Phase 1.35
      transactionTime: new Date().toISOString(),
      // Phase 2.4 PR13: balance snapshot
      accountCurrency: acctCurrencyFinal,
      balanceBefore: balanceBeforeRaw,
      balanceAfter:  balanceAfterRaw,
      debitAmount:   draft.account_debit_amount ? String(draft.account_debit_amount) : null,
      debitCurrency: draft.account_debit_currency ?? null,
    };
  });
}


/**
 * Phase 2.4 PR13: Reverse a balance arithmetic step.
 * If the transaction SUBTRACTED debit → balanceBefore = balanceAfter + debit.
 * If the transaction ADDED debit     → balanceBefore = balanceAfter - debit.
 *
 * SEC-02: BigInt scaled arithmetic (same as _numericAdd in screen-builder).
 * @internal
 */
function numericReverse(balanceAfter: string, debit: string, wasIncome: boolean): string {
  const toFixed4 = (s: string): string => {
    const neg = s.startsWith('-');
    const abs = neg ? s.slice(1) : s;
    const [int = '0', dec = ''] = abs.split('.');
    return `${neg ? '-' : ''}${int}.${dec.padEnd(4, '0').slice(0, 4)}`;
  };
  const parseScaled = (s: string): bigint => {
    const neg = s.startsWith('-');
    const abs = neg ? s.slice(1) : s;
    const [int = '0', dec = ''] = toFixed4(abs).split('.');
    return neg ? -BigInt(`${int}${dec}`) : BigInt(`${int}${dec}`);
  };
  const afterScaled = parseScaled(balanceAfter);
  const debitScaled = parseScaled(debit);
  // Reverse: income added debit, so before = after - debit.
  //          expense subtracted debit, so before = after + debit.
  const resultScaled = wasIncome ? afterScaled - debitScaled : afterScaled + debitScaled;
  const sign   = resultScaled < 0n ? '-' : '';
  const abs    = resultScaled < 0n ? -resultScaled : resultScaled;
  const absStr = abs.toString().padStart(5, '0');
  const intPart = absStr.slice(0, -4) || '0';
  const decPart = absStr.slice(-4).replace(/0+$/, '');
  return decPart ? `${sign}${intPart}.${decPart}` : `${sign}${intPart}`;
}

// ─────────────────────────────────────────────────────────────
// rejectDraft
// ─────────────────────────────────────────────────────────────

/**
 * Atomically reject a TransactionDraft.
 *
 * Flow:
 *   1. SELECT ... FOR UPDATE SKIP LOCKED — lock the draft row.
 *   2. Validate: must be pending_user.
 *   3. UPDATE status = 'rejected'.
 *   No Transaction is created.
 */
export async function rejectDraft(
  draftId: string,
  workspaceId: string,
  userId: string,
): Promise<ConfirmActionResult> {
  return withTenantTransaction(workspaceId, userId, async (client) => {
    // ── Step 1: Lock draft row ────────────────────────────────
    const lockResult = await client.query<{ id: string; status: string }>(
      `SELECT id, status
       FROM transaction_drafts
       WHERE id = $1 AND workspace_id = $2
       FOR UPDATE SKIP LOCKED`,
      [draftId, workspaceId],
    );

    if (lockResult.rows.length === 0) {
      const checkResult = await client.query<{ status: string }>(
        `SELECT status FROM transaction_drafts WHERE id = $1`,
        [draftId],
      );
      if (checkResult.rows.length === 0) {
        return { outcome: 'not_found' };
      }
      const existingStatus = checkResult.rows[0]?.status ?? 'unknown';
      return { outcome: 'already_processed', existingStatus };
    }

    const draft = lockResult.rows[0];
    if (!draft) return { outcome: 'not_found' }; // Defensive — should not happen after length check

    // ── Step 2: Validate status ───────────────────────────────
    if (draft.status !== 'pending_user') {
      return { outcome: 'already_processed', existingStatus: draft.status };
    }

    // ── Step 3: Update to rejected ────────────────────────────
    await client.query(
      `UPDATE transaction_drafts SET status = 'rejected', updated_at = NOW() WHERE id = $1`,
      [draftId],
    );

    console.log('[midas:draft-confirmation] Draft rejected', {
      draftId,
      workspaceId,
    });

    return { outcome: 'rejected' };
  });
}

// ─────────────────────────────────────────────────────────────
// resolveDefaultAccount — Phase 1.35
// ─────────────────────────────────────────────────────────────

/**
 * Resolve the default account for a transaction based on intent.
 * Pipeline:
 *   1. Check workspace.default_expense_account_id / default_income_account_id
 *   2. Fall back to LIMIT 1 from workspace accounts
 *   3. Create "Default" account if none exist
 */
async function resolveDefaultAccount(
  client: import('@midas/database').PoolClient,
  workspaceId: string,
  currency: string,
  intent: string | null,
): Promise<string> {
  // Step 1: Try workspace default by intent
  const defaultCol = (intent === 'income' || intent === 'debt_received')
    ? 'default_income_account_id'
    : 'default_expense_account_id';

  const wsDefault = await client.query<{ default_id: string | null }>(
    `SELECT ${defaultCol} AS default_id FROM workspaces WHERE id = $1`,
    [workspaceId],
  );
  const defaultId = wsDefault.rows[0]?.default_id;
  if (defaultId) {
    // Validate it still exists
    const check = await client.query<{ id: string }>(
      `SELECT id FROM account_sources WHERE id = $1 AND workspace_id = $2`,
      [defaultId, workspaceId],
    );
    if (check.rows.length > 0) {
      return defaultId;
    }
  }

  // Step 2: Fall back to LIMIT 1 — only active (non-deleted) accounts.
  // Phase LD: AND deleted_at IS NULL is required here so that a soft-deleted
  // onboarding placeholder (is_onboarding_placeholder = TRUE, deleted_at = NOW())
  // is never selected as the fallback account for a transaction.
  // Without this guard, transactions would be silently attached to a deleted account.
  const fallback = await client.query<{ id: string }>(
    `SELECT id FROM account_sources WHERE workspace_id = $1 AND deleted_at IS NULL LIMIT 1`,
    [workspaceId],
  );
  if (fallback.rows.length > 0 && fallback.rows[0]) {
    return fallback.rows[0].id;
  }

  // Step 3: Create "Default" account
  const newId = ulid();
  await client.query(
    `INSERT INTO account_sources (id, workspace_id, name, type, currency)
     VALUES ($1, $2, 'Default', 'manual'::account_source_type, $3)
     ON CONFLICT DO NOTHING`,
    [newId, workspaceId, currency],
  );
  const refetch = await client.query<{ id: string }>(
    `SELECT id FROM account_sources WHERE workspace_id = $1 AND name = 'Default' LIMIT 1`,
    [workspaceId],
  );
  return refetch.rows[0]?.id ?? newId;
}

// ─────────────────────────────────────────────────────────────
// fetchApprovedTransactionCard — Phase 1.35 already_processed fix
// ─────────────────────────────────────────────────────────────

/**
 * Fetch display data for an already-approved draft's transaction.
 * Used when already_processed fires with existingStatus = 'approved'.
 * Returns null if transaction is not found (race condition safety).
 *
 * SEC-03: withTenantTransaction enforces RLS isolation.
 * SEC-12: No amounts logged.
 */
export async function fetchApprovedTransactionCard(
  draftId: string,
  workspaceId: string,
  userId: string,
): Promise<{
  transactionId: string;
  amount: string;
  currency: string;
  categoryName: string;
  accountName: string;
  intent: string;
  itemName: string | null;
  // Phase 2.4 PR14: account snapshot fields
  accountCurrency: string | null;
  debitAmount: string | null;
  debitCurrency: string | null;
} | null> {
  return withTenantTransaction(workspaceId, userId, async (client) => {
    const txResult = await client.query<{
      id: string;
      original_amount: string;
      currency: string;
      transaction_intent: string;
      item_name: string | null;
      category_id: string | null;
      account_id: string | null;
      account_debit_amount: string | null;   // Phase 2.4 PR14
      account_debit_currency: string | null; // Phase 2.4 PR14
    }>(
      `SELECT t.id, t.original_amount, t.currency, t.transaction_intent, t.item_name,
              t.category_id, t.account_id,
              t.account_debit_amount, t.account_debit_currency
       FROM transactions t
       JOIN transaction_drafts d ON d.id = t.draft_id
       WHERE t.draft_id = $1 AND d.workspace_id = $2
       LIMIT 1`,
      [draftId, workspaceId],
    );

    const tx = txResult.rows[0];
    if (!tx) return null;

    const catResult = await client.query<{ name: string }>(
      `SELECT name FROM categories WHERE id = $1 AND workspace_id = $2`,
      [tx.category_id, workspaceId],
    );
    const acctResult = await client.query<{ name: string; currency: string }>(
      `SELECT name, currency FROM account_sources WHERE id = $1 AND workspace_id = $2`,
      [tx.account_id, workspaceId],
    );

    return {
      transactionId: tx.id,
      // eslint-disable-next-line @typescript-eslint/no-unnecessary-type-conversion,@typescript-eslint/no-unnecessary-condition -- runtime type is Decimal, not string
      amount: String(tx.original_amount ?? '0'),  // Decimal → string (same setTypeParser fix)
      currency: tx.currency,
      categoryName: catResult.rows[0]?.name ?? 'Другое',
      accountName: acctResult.rows[0]?.name ?? 'Счёт',
      intent: tx.transaction_intent,
      itemName: tx.item_name ?? null,
      // Phase 2.4 PR14: account snapshot
      accountCurrency: acctResult.rows[0]?.currency ?? null,
      debitAmount:   tx.account_debit_amount ? String(tx.account_debit_amount) : null,
      debitCurrency: tx.account_debit_currency ?? null,
    };
  });
}
