/**
 * Draft Confirmation Service — Phase 1.6-B / Phase 1.8-A / Phase 1.25 / Phase 1.35
 *
 * Implements atomic approve/reject for TransactionDraft records.
 *
 * Phase 1.8-A addition:
 *   - parsed_intent is now fetched from the draft during SELECT FOR UPDATE.
 *   - transaction_intent is written to transactions during INSERT.
 *   - If parsed_intent IS NULL when a draft is approved, the approval fails safely
 *     with outcome 'intent_missing'. No Transaction is created. This prevents
 *     silent data corruption — every Transaction must have a known intent.
 *
 * Race condition protection:
 *   - SELECT ... FOR UPDATE SKIP LOCKED prevents two concurrent workers from
 *     processing the same draft simultaneously.
 *   - The draft status is checked inside the locked transaction. If status is
 *     not 'pending_user', the operation is a no-op (idempotent).
 *   - transactions.draft_id has UNIQUE constraint → second INSERT would fail
 *     even if SELECT FOR UPDATE fails (defence in depth).
 *
 * SEC-03: ALL DB ops use withTenantTransaction(workspaceId, userId, fn).
 * SEC-02: No float arithmetic. Amount read from draft.parsed_amount (NUMERIC in DB).
 * ADR-004: Transaction ID = ULID generated by backend.
 * Draft state machine (migration 1777973834059): DB trigger enforces valid transitions.
 */

import { ulid } from 'ulid';
import { withTenantTransaction } from '@midas/database';
import { resolveCategory } from './category-resolver.service.js';

// ─────────────────────────────────────────────────────────────
// Types
// ─────────────────────────────────────────────────────────────

export type ConfirmActionResult =
  | {
      outcome: 'approved';
      transactionId: string;
      // Phase 1.34: display data for rich post-confirmation card
      amount: string;           // NUMERIC string from DB (SEC-02)
      currency: string;         // e.g. 'USDT'
      categoryName: string;     // resolved name or fallback
      accountName: string;      // resolved name or fallback
      intent: string;           // transaction_intent
      itemName: string | null;  // Phase 1.35: item/product/merchant name
      transactionTime: string;  // ISO string
    }
  | { outcome: 'rejected' }
  | {
      outcome: 'already_processed';
      existingStatus: string;
      // Present when existingStatus === 'approved' — for rich re-display
      approvedCard?: {
        transactionId: string;
        amount: string;
        currency: string;
        categoryName: string;
        accountName: string;
        intent: string;
        itemName: string | null;
      };
    }
  | { outcome: 'not_found' }
  | { outcome: 'expired' }
  | { outcome: 'intent_missing' }; // Phase 1.8-A: draft has NULL parsed_intent — cannot create Transaction

// ─────────────────────────────────────────────────────────────
// approveDraft
// ─────────────────────────────────────────────────────────────

/**
 * Atomically approve a TransactionDraft.
 *
 * Flow (all inside one withTenantTransaction):
 *   1. SELECT ... FOR UPDATE SKIP LOCKED — lock the draft row.
 *      If another worker has it locked, SKIP LOCKED returns 0 rows → no-op.
 *   2. Validate: draft must exist, belong to workspace, be pending_user, and not expired.
 *   3. Phase 1.8-A: validate parsed_intent is not NULL. If NULL → return intent_missing.
 *   4. UPDATE transaction_drafts SET status = 'approved'.
 *      The DB trigger (enforce_draft_state_machine) also validates expiry.
 *   5. INSERT INTO transactions with transaction_intent (Phase 1.8-A: explicit, no default).
 *
 * @param draftId - ULID of the draft to approve
 * @param workspaceId - Workspace ID (SEC-03: from backend session, not from callback_data)
 * @param userId - User ID for RLS context (SEC-03)
 * @returns ConfirmActionResult with outcome
 */
export async function approveDraft(
  draftId: string,
  workspaceId: string,
  userId: string,
): Promise<ConfirmActionResult> {
  return withTenantTransaction(workspaceId, userId, async (client) => {
    // ── Step 1: Lock draft row for atomic update ──────────────
    // SKIP LOCKED: if another worker already has this row locked,
    // we get 0 rows and return immediately (not an error — idempotent).
    const lockResult = await client.query<{
      id: string;
      workspace_id: string;
      status: string;
      parsed_amount: string | null;
      parsed_currency: string | null;
      parsed_intent: string | null;  // Phase 1.8-A: must be non-NULL for Transaction creation
      parsed_account_hint: string | null; // Phase 1.31
      parsed_category_hint: string | null; // Phase 1.35
      item_name: string | null;            // Phase 1.35
      account_id: string | null;          // Phase 1.31: set by ia: callback before approval
      expires_at: string;
    }>(
      `SELECT id, workspace_id, status, parsed_amount, parsed_currency, parsed_intent,
              parsed_account_hint, parsed_category_hint, item_name, account_id, expires_at
       FROM transaction_drafts
       WHERE id = $1 AND workspace_id = $2
       FOR UPDATE SKIP LOCKED`,
      [draftId, workspaceId],
    );

    // ── Step 2: Check if we got the lock ─────────────────────
    if (lockResult.rows.length === 0) {
      // Either not found (wrong workspace) or locked by another worker.
      // Query without lock to distinguish:
      const checkResult = await client.query<{ status: string }>(
        `SELECT status FROM transaction_drafts WHERE id = $1`,
        [draftId],
      );
      if (checkResult.rows.length === 0) {
        return { outcome: 'not_found' };
      }
      // Row exists but locked by another worker → they're processing it.
      const existingStatus = checkResult.rows[0]?.status ?? 'unknown';
      return { outcome: 'already_processed', existingStatus };
    }

    const draft = lockResult.rows[0];
    if (!draft) return { outcome: 'not_found' }; // Defensive — should not happen after length check

    // ── Step 3: Validate status ───────────────────────────────
    if (draft.status !== 'pending_user') {
      return { outcome: 'already_processed', existingStatus: draft.status };
    }

    // ── Step 4: Check expiry ──────────────────────────────────
    const expiresAt = new Date(draft.expires_at);
    if (expiresAt <= new Date()) {
      // Update to expired to clean up state — DB trigger allows pending_user → expired
      await client.query(
        `UPDATE transaction_drafts SET status = 'expired', updated_at = NOW() WHERE id = $1`,
        [draftId],
      );
      return { outcome: 'expired' };
    }

    // ── Step 5: Phase 1.8-A — Validate intent before committing ──────────────────
    // parsed_intent must not be NULL. A Transaction without a known intent is
    // semantically invalid and would corrupt future /report queries.
    // Fail safely: do NOT update draft status, do NOT create Transaction.
    // The user can resend the message to create a new draft with valid intent.
    if (draft.parsed_intent === null) {
      console.warn('[midas:draft-confirmation] Approval blocked: parsed_intent is NULL', {
        draftId,
        workspaceId,
        // No raw_text logged (SEC-12)
      });
      return { outcome: 'intent_missing' };
    }

    // ── Step 6: Update draft status to approved ───────────────
    // DB trigger (enforce_draft_state_machine) will re-validate expiry and terminal state.
    await client.query(
      `UPDATE transaction_drafts SET status = 'approved', updated_at = NOW() WHERE id = $1`,
      [draftId],
    );

    // ── Step 7: Create Transaction from draft ─────────────────
    // SEC-02: parsed_amount is a NUMERIC string from DB — passed directly to NUMERIC column.
    // No parseFloat(), no Number() — the DB handles precision.
    // Phase 1.6-B: exchange_rate = 1, base_amount = parsed_amount (same currency).
    // Full multi-currency support: Phase 2 (ADR-009 exchange rate snapshots).
    const transactionId = ulid(); // ADR-004: ULID generated by backend (SEC-01)

    // Phase 1.25: Fetch workspace default_currency BEFORE resolving transaction currency.
    // Used as fallback when AI does not parse an explicit currency from the message.
    // Replaces hardcoded 'USD' fallback — ensures transactions use the workspace's
    // configured default (e.g. USDT for new users, or whatever /settings currency set).
    const wsResult = await client.query<{ default_currency: string }>(
      `SELECT default_currency FROM workspaces WHERE id = $1`,
      [workspaceId],
    );
    const baseCurrency = wsResult.rows[0]?.default_currency ?? 'USDT';

    // Workspace default_currency for base_currency (same SELECT result reused above).
    // Phase 1.25: fallback is baseCurrency (workspace default), not hardcoded 'USD'.
    const currency = draft.parsed_currency ?? baseCurrency;

    // Determine category_id: Phase 1.35 — use resolver pipeline.
    // Pipeline: exact match → alias map → auto-create → fallback "Другое".
    const categoryId = await resolveCategory(client, workspaceId, draft.parsed_category_hint);

    // Determine account_id: Phase 1.31 — use draft.account_id if set by ia: handler.
    // Phase 1.35: Fall back to workspace default account by intent.
    // Otherwise fall back to workspace first account source or create a Default.
    let accountId: string;
    if (draft.account_id) {
      // Phase 1.31: account was resolved inline by user via ia: callback.
      const acctCheck = await client.query<{ id: string }>(
        `SELECT id FROM account_sources WHERE id = $1 AND workspace_id = $2`,
        [draft.account_id, workspaceId],
      );
      if (acctCheck.rows.length > 0) {
        accountId = draft.account_id;
      } else {
        // IDOR guard: account not in workspace — fall back to default
        accountId = await resolveDefaultAccount(client, workspaceId, currency, draft.parsed_intent);
      }
    } else {
      // Phase 1.35: Use workspace default account by intent.
      accountId = await resolveDefaultAccount(client, workspaceId, currency, draft.parsed_intent);
    }

    await client.query(
      `INSERT INTO transactions (
        id,
        workspace_id,
        original_amount,
        currency,
        exchange_rate,
        base_currency,
        base_amount,
        category_id,
        account_id,
        draft_id,
        item_name,
        transaction_time,
        transaction_intent,
        rate_source,
        created_at
      ) VALUES (
        $1, $2,
        $3::NUMERIC,        -- original_amount from draft.parsed_amount (SEC-02: no float)
        $4,
        1::NUMERIC,         -- exchange_rate = 1:1 (Phase 1.6-B; multi-currency Phase 2)
        $5,
        $3::NUMERIC,        -- base_amount = original_amount (same currency, Phase 1.6-B)
        $6,                 -- category_id (Phase 1.35: from resolver)
        $7,                 -- account_id
        $8,                 -- draft_id (UNIQUE FK)
        $9,                 -- item_name (Phase 1.35)
        NOW(),
        $10,                -- transaction_intent (Phase 1.8-A: explicit, no default)
        'none',             -- rate_source: Phase 1.6-B placeholder (ADR-009 Phase 2)
        NOW()
      )`,
      [
        transactionId,              // $1 — ULID (ADR-004, SEC-01: not from AI)
        workspaceId,                // $2 — SEC-03: from backend session
        String(draft.parsed_amount ?? '0'), // $3 — safe NUMERIC string (SEC-02)
        currency,                   // $4
        baseCurrency,               // $5
        categoryId,                 // $6 — Phase 1.35: from resolver pipeline
        accountId,                  // $7
        draftId,                    // $8
        draft.item_name ?? null,    // $9 — Phase 1.35: item/product/merchant name
        draft.parsed_intent,        // $10 — Phase 1.8-A: non-NULL validated in Step 5
      ],
    );

    console.log('[midas:draft-confirmation] Draft approved and Transaction created', {
      draftId,
      transactionId,
      workspaceId,
      transactionIntent: draft.parsed_intent, // safe to log: classification value (SEC-12)
      // amount deliberately NOT logged (SEC-12)
    });

    // Phase 1.34: Fetch display names for rich post-confirmation card.
    // These are read-only lookups — no business logic change.
    const catNameResult = await client.query<{ name: string }>(
      `SELECT name FROM categories WHERE id = $1 AND workspace_id = $2`,
      [categoryId, workspaceId],
    );
    const acctNameResult = await client.query<{ name: string }>(
      `SELECT name FROM account_sources WHERE id = $1 AND workspace_id = $2`,
      [accountId, workspaceId],
    );

    return {
      outcome: 'approved',
      transactionId,
      amount: draft.parsed_amount ?? '0',
      currency,
      categoryName: catNameResult.rows[0]?.name ?? 'Другое',
      accountName: acctNameResult.rows[0]?.name ?? 'Счёт',
      intent: draft.parsed_intent,  // Validated non-null at Step 5
      itemName: draft.item_name ?? null,  // Phase 1.35
      transactionTime: new Date().toISOString(),
    };
  });
}

// ─────────────────────────────────────────────────────────────
// rejectDraft
// ─────────────────────────────────────────────────────────────

/**
 * Atomically reject a TransactionDraft.
 *
 * Flow:
 *   1. SELECT ... FOR UPDATE SKIP LOCKED — lock the draft row.
 *   2. Validate: must be pending_user.
 *   3. UPDATE status = 'rejected'.
 *   No Transaction is created.
 */
export async function rejectDraft(
  draftId: string,
  workspaceId: string,
  userId: string,
): Promise<ConfirmActionResult> {
  return withTenantTransaction(workspaceId, userId, async (client) => {
    // ── Step 1: Lock draft row ────────────────────────────────
    const lockResult = await client.query<{ id: string; status: string }>(
      `SELECT id, status
       FROM transaction_drafts
       WHERE id = $1 AND workspace_id = $2
       FOR UPDATE SKIP LOCKED`,
      [draftId, workspaceId],
    );

    if (lockResult.rows.length === 0) {
      const checkResult = await client.query<{ status: string }>(
        `SELECT status FROM transaction_drafts WHERE id = $1`,
        [draftId],
      );
      if (checkResult.rows.length === 0) {
        return { outcome: 'not_found' };
      }
      const existingStatus = checkResult.rows[0]?.status ?? 'unknown';
      return { outcome: 'already_processed', existingStatus };
    }

    const draft = lockResult.rows[0];
    if (!draft) return { outcome: 'not_found' }; // Defensive — should not happen after length check

    // ── Step 2: Validate status ───────────────────────────────
    if (draft.status !== 'pending_user') {
      return { outcome: 'already_processed', existingStatus: draft.status };
    }

    // ── Step 3: Update to rejected ────────────────────────────
    await client.query(
      `UPDATE transaction_drafts SET status = 'rejected', updated_at = NOW() WHERE id = $1`,
      [draftId],
    );

    console.log('[midas:draft-confirmation] Draft rejected', {
      draftId,
      workspaceId,
    });

    return { outcome: 'rejected' };
  });
}

// ─────────────────────────────────────────────────────────────
// resolveDefaultAccount — Phase 1.35
// ─────────────────────────────────────────────────────────────

/**
 * Resolve the default account for a transaction based on intent.
 * Pipeline:
 *   1. Check workspace.default_expense_account_id / default_income_account_id
 *   2. Fall back to LIMIT 1 from workspace accounts
 *   3. Create "Default" account if none exist
 */
async function resolveDefaultAccount(
  client: import('@midas/database').PoolClient,
  workspaceId: string,
  currency: string,
  intent: string | null,
): Promise<string> {
  // Step 1: Try workspace default by intent
  const defaultCol = (intent === 'income' || intent === 'debt_received')
    ? 'default_income_account_id'
    : 'default_expense_account_id';

  const wsDefault = await client.query<{ default_id: string | null }>(
    `SELECT ${defaultCol} AS default_id FROM workspaces WHERE id = $1`,
    [workspaceId],
  );
  const defaultId = wsDefault.rows[0]?.default_id;
  if (defaultId) {
    // Validate it still exists
    const check = await client.query<{ id: string }>(
      `SELECT id FROM account_sources WHERE id = $1 AND workspace_id = $2`,
      [defaultId, workspaceId],
    );
    if (check.rows.length > 0) {
      return defaultId;
    }
  }

  // Step 2: Fall back to LIMIT 1
  const fallback = await client.query<{ id: string }>(
    `SELECT id FROM account_sources WHERE workspace_id = $1 LIMIT 1`,
    [workspaceId],
  );
  if (fallback.rows.length > 0 && fallback.rows[0]) {
    return fallback.rows[0].id;
  }

  // Step 3: Create "Default" account
  const newId = ulid();
  await client.query(
    `INSERT INTO account_sources (id, workspace_id, name, type, currency)
     VALUES ($1, $2, 'Default', 'manual'::account_source_type, $3)
     ON CONFLICT DO NOTHING`,
    [newId, workspaceId, currency],
  );
  const refetch = await client.query<{ id: string }>(
    `SELECT id FROM account_sources WHERE workspace_id = $1 AND name = 'Default' LIMIT 1`,
    [workspaceId],
  );
  return refetch.rows[0]?.id ?? newId;
}

// ─────────────────────────────────────────────────────────────
// fetchApprovedTransactionCard — Phase 1.35 already_processed fix
// ─────────────────────────────────────────────────────────────

/**
 * Fetch display data for an already-approved draft's transaction.
 * Used when already_processed fires with existingStatus = 'approved'.
 * Returns null if transaction is not found (race condition safety).
 *
 * SEC-03: withTenantTransaction enforces RLS isolation.
 * SEC-12: No amounts logged.
 */
export async function fetchApprovedTransactionCard(
  draftId: string,
  workspaceId: string,
  userId: string,
): Promise<{
  transactionId: string;
  amount: string;
  currency: string;
  categoryName: string;
  accountName: string;
  intent: string;
  itemName: string | null;
} | null> {
  return withTenantTransaction(workspaceId, userId, async (client) => {
    const txResult = await client.query<{
      id: string;
      amount: string;
      currency: string;
      transaction_intent: string;
      item_name: string | null;
      category_id: string | null;
      account_source_id: string | null;
    }>(
      `SELECT t.id, t.amount, t.currency, t.transaction_intent, t.item_name,
              t.category_id, t.account_source_id
       FROM transactions t
       JOIN transaction_drafts d ON d.id = t.draft_id
       WHERE t.draft_id = $1 AND d.workspace_id = $2
       LIMIT 1`,
      [draftId, workspaceId],
    );

    const tx = txResult.rows[0];
    if (!tx) return null;

    const catResult = await client.query<{ name: string }>(
      `SELECT name FROM categories WHERE id = $1 AND workspace_id = $2`,
      [tx.category_id, workspaceId],
    );
    const acctResult = await client.query<{ name: string }>(
      `SELECT name FROM account_sources WHERE id = $1 AND workspace_id = $2`,
      [tx.account_source_id, workspaceId],
    );

    return {
      transactionId: tx.id,
      amount: tx.amount,
      currency: tx.currency,
      categoryName: catResult.rows[0]?.name ?? 'Другое',
      accountName: acctResult.rows[0]?.name ?? 'Счёт',
      intent: tx.transaction_intent,
      itemName: tx.item_name ?? null,
    };
  });
}
